config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	
	attr_accessor :remember_token, :activation_token
	before_save   :downcase_email
	before_create :create_activation_digest

    validates(:name, presence: true, length: { maximum: 50 })
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    #validates(:email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false })
    validates :email, presence: true, :if => :empty?
    validates :email, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false},  :if => :invalid?

    has_secure_password
  	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

      # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(attribute, token)
      digest = send("#{attribute}_digest")
  return false if digest.nil?
      BCrypt::Password.new(digest).is_password?(token)
  end

  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end
    
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  private

    def empty?
      (self.email).empty?
    end

    def invalid?
      !self.email.empty?
    end

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

    

end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController

	def edit
    	user = User.find_by(email: params[:email])
    	if user && !user.activated? && user.authenticated?(:activation, params[:id])
      		user.activate
      		log_in user
      		flash[:success] = "Account activated!"
      		redirect_to user
    	else
    		flash[:danger] = "Invalid activation link"
    		redirect_to root_url
    	end
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def hello
    render html: "hello, world!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_back_or user
      else
        message  = "Account not activated. "
        message += "Check your email for the activation link."
        flash[:warning] = message
        redirect_to root_url
      end

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      # Handle a successful save.
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end

  
  
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

  def user_params
  
    params.require(:user).permit(:name, :email, :password,:password_confirmation)
    
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end


end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
  	forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    The
    %a{:href => "https://www.railstutorial.org/"} Ruby on Rails Tutorial App
    by
    %a{:href => "http://www.michaelhartl.com/"} Viral Parekh
  %nav
    %ul
      %li= link_to "About",   about_path
      %li= link_to "Contact", contact_path
      %li
        %a{:href => "http://news.railstutorial.org/"} News

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to "My First App", root_path, id: "logo"
      %nav
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Home", root_path
          %li= link_to "Help", help_path
          - if logged_in?
            %li= link_to "Users", users_path
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Log out", logout_path, method: :delete
          - else
            %li= link_to "Log in", login_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.haml
%head
  %title= full_title(yield(:title))
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %title= full_title(yield(:title))
  = render 'layouts/shim'
%body
  = render 'layouts/header'
  .container
    - flash.each do |message_type, message|
      %div{:class => "alert alert-#{message_type}"}= message
    = yield
  = render 'layouts/footer'
  = debug(params) if Rails.env.development?

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(@user.errors.count, "error")}.
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

app/views/static_pages/about.html.haml
- provide(:title, "About")
%h1 About
%p
  The
  %a{:href => "https://www.railstutorial.org/"}
    %em
      Ruby on Rails
      Tutorial
  is a
  %a{:href => "https://www.railstutorial.org/book"} book
  and
  %a{:href => "http://screencasts.railstutorial.org/"} screencast series
  to teach web development with
  = succeed "." do
    %a{:href => "http://rubyonrails.org/"} Ruby on Rails

app/views/static_pages/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact
%p
  Contact the Ruby on Rails Tutorial about the sample app at the
  = succeed "." do
    %a{:href => "https://www.railstutorial.org/contact"} contact page

app/views/static_pages/help.html.haml
- provide(:title, "Help")
%h1 Help
%p
  Get help on the Ruby on Rails Tutorial at the
  = succeed "." do
    %a{:href => "https://www.railstutorial.org/help"} Rails Tutorial help section
  = succeed "." do
    %a{:href => "https://www.railstutorial.org/book"}
      %em Ruby on Rails Tutorial
      book

app/views/static_pages/home.html.haml
.center.jumbotron
  %h1 Welcome to My First App
  %h2
    This is the home page for the
    %a{:href => "https://www.railstutorial.org/"} Ruby on Rails Tutorial
    sample application.
  = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"
= link_to image_tag("rails.png", alt: "Rails logo"), |
  'http://rubyonrails.org/'                          |
/%img{:alt => "kitten", :src => "/assets/kitten.jpg"}/

app/views/users/_user.html.haml
%li
  = gravatar_for user, size: 50
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    | #{link_to "delete", user, method: :delete, data: { confirm: "You sure?" }}

app/views/users/edit.html.haml
- provide(:title, "Edit user")
%h1 Update your profile
.row
  .col-md-6.col-md-offset-3
    = form_for(@user) do |f|
      = render 'shared/error_messages'
      = f.label :name
      = f.text_field :name, class: 'form-control'
      = f.label :email
      = f.email_field :email, class: 'form-control'
      = f.label :password
      = f.password_field :password, class: 'form-control'
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation, class: 'form-control'
      = f.submit "Save changes", class: "btn btn-primary"
    .gravatar_edit
      = gravatar_for @user
      %a{:href => "http://gravatar.com/emails", :target => "_blank"} change

app/views/users/index.html.haml
- provide(:title, 'All users')
%h1 All users
= will_paginate
%ul.users
  = render @users
= will_paginate

app/views/users/new.html.haml
- provide(:title, 'Sign up')
%h1 Sign up
.row
  .col-md-6.col-md-offset-3
    = form_for(@user, url: signup_path) do |f|
      = render 'shared/error_messages'
      = f.label :name
      = f.text_field :name, class: 'form-control'
      = f.label :email
      = f.email_field :email, class: 'form-control'
      = f.label :password
      = f.password_field :password, class: 'form-control'
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation, class: 'form-control'
      = f.submit "Create my account", class: "btn btn-primary"

app/views/users/show.html.haml
- provide(:title, @user.name)
.row
  %aside.col-md-4
    %section.user_info
      %h1
        = gravatar_for @user
        = @user.name